transform:

  # Only retain the player _id
  cs_player_ids_to_nhl_landing_urls:
    mapping: 
      csid: _id
      url: 
        template: "https://api-web.nhle.com/v1/player/%s/landing"
        args: id

  # Get fresh NHL data
  nhl_player_to_person:
    mapping:
      id: csid # from the previous step
      first_name: firstName.default # handle subpaths
      last_name: lastName.default # handle subpaths
      full_name: 
        action: concat_space # str concat, default with space
        args: [ firstName.default, lastName.default ] 
      birthdate: birthDate
      birth_city: birthCity.default
      birth_state_province_code: 
        query: "SELECT code FROM state_province_code WHERE name LIKE %s"
        args: birthStateProvince.default
        take: 0 # take the first response of the resulting list only
      birth_state_country_code: birthCountry.default

    # notice there is not player_id here, 
    # the program needs to keep track of the mapping
      
  nhl_player_to_player:
    src_label: nhl_player
    dst_model: player
    mapping:
      person_id: csid # from the previous step
      player_id: playerId
      shoots_catches: shootsCatches
      positions: 
        action: to_list
        args: position

      